### ISSUE TITLE
Cannot download blastdb (404, wildcards)

### ISSUE THREAD

**Issue by josephwb** [mkandziora/PhylUp#10]
I tried the command on the [wiki](https://github.com/mkandziora/PhylUp/wiki/01-Install-PhylUp):
```
wget 'https://ftp.ncbi.nlm.nih.gov/blast/db/nt.*'
```
and get the result:
```
Warning: wildcards not supported in HTTP.
--2021-04-07 11:22:24--  https://ftp.ncbi.nlm.nih.gov/blast/db/nt.*
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 2607:f220:41e:250::12, 2607:f220:41f:250::230, 165.112.9.230, ...
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|2607:f220:41e:250::12|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-04-07 11:22:25 ERROR 404: Not Found.
```
There appear to be 34 matching files (i.e., nt.01.tar.gz -> nt.34.tar.gz),  so this can be looped over. I guess the names of the available files must first be fetched. Or do a while loop, downloading and incrementing a counter until you hit a file which does not exist (here, nt.35.tar.gz)?

**Comment by josephwb** [comment]
fwiw this is what I did (after finding the number of files available):
```
#!/bin/bash
for i in {01..34};
  do echo $i;
  wget https://ftp.ncbi.nlm.nih.gov/blast/db/nt.$i.tar.gz
done
```

**Comment by mkandziora** [comment]
Hi Joseph,

Thanks for spotting this issue. 

I think I fixed the wiki tutorial command (at least for Linux systems) by removing the ' sign before and after the url: `wget https://ftp.ncbi.nlm.nih.gov/blast/db/nt.*`. The problem with a for loop is that the numbers of the nt database increases over time as more and more sequences are uploaded to Genbank, thus the wildcard approach.

**Comment by josephwb** [comment]
I get the same results with that: wildcards do not work. I am using Ubuntu 18.04.

Yes, a changing number is a problem. The best I can think of is to download the filenames available, process that, and finally loop.

**Comment by mkandziora** [comment]
Ah, yes. I missed something, ftp instead of https at the beginning: `wget ftp://ftp.ncbi.nlm.nih.gov/blast/db/nt.*`.

**Comment by josephwb** [comment]
Doh yup that's it. Sorry I missed it.
