### ISSUE TITLE
taxonomic rank database question

### ISSUE THREAD

**Issue by josephwb** [mkandziora/PhylUp#12]
Is the taxonomic rank database supposed to be made in the blastdb directory? The [wiki](https://github.com/mkandziora/PhylUp/wiki/01-Install-PhylUp#4-install-a-local-instance-of-the-blast-database) instructs moving the files (names.dmp and nodes.dmp) into the `data` directory, but it is not clear where this directory should be.

**Comment by josephwb** [comment]
Oh, is this referring to the repo's `data` directory?

**Comment by josephwb** [comment]
Ok, reading `tests_setup.py` code it seems that things are referring to the repo's `data` directory.

Sorry for polluting your Issues with my inanity.

**Comment by mkandziora** [comment]
Clarified this in the wiki - better to be explicit
