### ISSUE TITLE
example_concat failure

### ISSUE THREAD

**Issue by josephwb** [mkandziora/PhylUp#16]
[I am obviously working through the examples. I hope this is not too annoying.]

How do I run the concatenation example? A blind running of the script delivers the error:
```
$ python3 example_concat.py 
Building concat config object
Traceback (most recent call last):
  File "example_concat.py", line 14, in <module>
    config = concat_config.ConcatConfigObj(configfi, workdir_comb)
  File "/home/josephwb/Downloads/PhylUp/src/concat/Concat/concat_config.py", line 47, in __init__
    self.run_modeltest = config['concat']['run_modeltest']
  File "/usr/lib/python3.6/configparser.py", line 1233, in __getitem__
    raise KeyError(key)
KeyError: 'run_modeltest'
```
 which suggests modeltest is the issue. But I looked at the code and it is looking for `modeltest-ng` which I have installed and on my PATH.

However, in looking at `example_config.py` itself it looks like the raw data are missing? For example, the directories `workdir_its` ('Senecioneae_its') and `workdir_ets` ('Senecioneae_ets') are not present, and the `workdir_comb` ("remote/concat_nr") is completely empty. Is there a step I am missing to populate these data?

Thanks again.

**Comment by mkandziora** [comment]
[Thanks for going through them, this is very helpful - I know the program to well to spot inconsistencies and unclear documentation]

The example_concat.py should probably be removed from this repository. I added it as an example of how you could concatenate independent PhylUp runs. For this the independent PhylUp runs first would need to be run. This file basically calls the small package "phylogenetic_concatenation" I wrote to concatenate single gene alignments (either using the PhylUp setup or just alignments files). The example workdirs are really just examples - you would need to replace them with your output folders.

Nevertheless, your run_modeltest error is unrelated to that - I forgot to update the `concat.config` file in the data folder to include the run_modeltest configuration setting. Fixed.

**Comment by josephwb** [comment]
Ok, thanks.

I thought that was what was missing from the config file, but no config file in the repository includes `run_modeltest` at all (either True or False). In fact, the wiki does not mention the `run_modeltest` config argument either. The [settings](https://github.com/mkandziora/PhylUp/wiki/03-Settings-options) page mentions `modeltest_criteria`, but not turning on model testing itself (unless specifying a criterion indirectly sets `run_modeltest = True`)?

**Comment by mkandziora** [comment]
Yes, this is currently not optional for PhylUp. When you are running `example_config.py` you are basically not running PhylUp code, but the [phylogenetic_concatentation](https://github.com/mkandziora/phylogenetic_concatenation/blob/master/data/concat.config). I will remove it from the examples and link to the phylogenetic_concatenation page instead to make this less confusing.
