### ISSUE TITLE
peer code review?

### ISSUE THREAD

**Issue by josephwb** [mkandziora/PhylUp#22]
Hi @mkandziora.

It occurred to me that you might want to submit your package to a thorough peer view with [pyOpenSci](https://www.pyopensci.org/)? A package that passes through that vetting would definitely impress journal reviewers. I am finding ways to break thing, but that is because I don't really know what I am doing. The folks at pyOpenSci will find entire new ways to break things (and consequently make your package that much more robust).

Anyway, just an idea. Thanks for all of the feedback you've been giving me,

**Comment by mkandziora** [comment]
Hi @josephwb,

Thanks for all your feedback while running the code. This is very helpful. Your pyOpenSci suggestion is probably the way forward - It is much easier to break things unintentionally than I anticipated...(:

**Comment by josephwb** [comment]
Sounds good.

I know the rOpenSci folks do a stellar job, and would wager the pyOpenSci process is similar.
