### ISSUE TITLE
warning with example_unpublished

### ISSUE THREAD

**Issue by josephwb** [mkandziora/PhylUp#23]
I installed the taxonomy database following the [wiki](https://github.com/mkandziora/PhylUp/wiki/01-Install-PhylUp#4-install-a-local-instance-of-the-blast-database). However, when I run `example_unpublished.py`the following warning keeps getting printed:
```
Warning: [blastn] Taxonomy name lookup from taxid requires installation of taxdb database with ftp://ftp.ncbi.nlm.nih.gov/blast/db/taxdb.tar.gz
```
Things seem to be running fine. Should I be worried about this warning?

**Comment by mkandziora** [comment]
Nothing to worry about. I just do not manage to make blast silent.

**Comment by josephwb** [comment]
Ok, thanks.
